# Конфигурационный файл для камеры SIT

# Файл читается программой «на лету», изменения применяются без перезапуска сервера

# О синтаксисе YAML файлов см. напр. https://en.wikipedia.org/wiki/YAML#Syntax

# По вопросам можно обращаться на gosha.vaiman@gmail.com

# Каждый элемент верхнего уровня — сценарий работы камеры, все они исполняются одновременно!
# Это позволяет, например, каждые 20 секунд делать снимок невысокого качества (высокий гейн,
# низкая выдержка) для стриминга в веб интерфейс, и независимо от этого каждые 5 минут — снимок
# высокого качества, к которому применять сложную обработку и сохранять результаты в FITS-файл

# Все времена записываются в секундах. значения гейна — в относительных единицах

# 1. Единственный «сценарий» на текущий момент — эти снимки не сохраняются в файлы, а стримятся
# напрямую в веб-интерфейс. Доступ по адресу ???
preview:
    enabled: True
    period: 5
    exposure: 0.03
    gain: 20
    # rgb | greyscale
    color_mode: rgb

# Для тестирования, на сервере должно стоять enabled: False
testing:
    enabled: False
    period: 12.5
    exposure: 0.01
    gain: 1